gui:
  nerdFontsVersion: "3"

os:
  openLink: "start {{link}}"

git:
  overrideGpg: true # My gpg won't show a password prompt. lg disable some features if I am on gpg
  pagers:
    - colorArg: never
      pager: delta --dark --paging=never
    - externalDiffCommand: difft --color=always --display=inline --syntax-highlight=off
